# Generated by Django 4.0.2 on 2022-02-15 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenseinformation',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
