# Generated by Django 4.0.2 on 2022-02-16 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget_app', '0004_alter_expenseinformation_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenseinformation',
            name='category',
            field=models.CharField(choices=[('Zakupy', 'Zakupy'), ('Kosmetyki', 'Kosmetyki'), ('Odzież', 'Odzież'), ('Transport', 'Transport'), ('Rozrywka', 'Rozrywka'), ('Edukacja', 'Edukacja'), ('Zdrowie', 'Zdrowie'), ('Inne', 'Inne')], default='Inne', max_length=10),
        ),
    ]
