# Generated by Django 4.0.2 on 2022-02-16 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget_app', '0005_alter_expenseinformation_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenseinformation',
            name='expense',
            field=models.PositiveIntegerField(),
        ),
    ]
