# Generated by Django 4.0.2 on 2022-02-16 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget_app', '0008_alter_expenseinformation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenseinformation',
            name='date',
            field=models.DateField(default='2022.02.16'),
        ),
    ]
